CREATE TABLE TB_GENDER (
    ID_GENDER INT NOT NULL PRIMARY KEY,
    NAME VARCHAR(10) NOT NULL
);

CREATE TABLE TB_PERSON (
    ID_PERSON INT NOT NULL PRIMARY KEY,
    ID_GENDER INT NOT NULL,
    FULL_NAME VARCHAR(255) NOT NULL,
    BIRTHDATE DATE,
    FOREIGN KEY (ID_GENDER) REFERENCES TB_GENDER(ID_GENDER)
);

CREATE SEQUENCE TB_PERSON_SEQ;

INSERT INTO TB_GENDER (ID_GENDER, NAME) VALUES (1, 'Male');
INSERT INTO TB_GENDER (ID_GENDER, NAME) VALUES (2, 'Female');
INSERT INTO TB_GENDER (ID_GENDER, NAME) VALUES (3, 'Other');
